# Generated by Django 4.1 on 2023-01-08 10:09

from django.db import migrations, models
import django.db.models.deletion
import rooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customers_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=20)),
                ('room_num', models.IntegerField()),
                ('room_cover_pic', models.FileField(null=True, upload_to=rooms.models.user_directory_path, verbose_name='图片')),
                ('introduction', models.CharField(max_length=1024)),
                ('is_occupied', models.BooleanField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_pic', models.CharField(max_length=1024)),
                ('describe', models.CharField(max_length=1024)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCheckIns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.IntegerField()),
                ('is_confirmed', models.BooleanField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCheckInCustomers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customers')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
            ],
        ),
    ]
