# Generated by Django 4.1 on 2023-01-29 13:54

from django.db import migrations, models
import django.db.models.deletion
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheckins',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomcheckins',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.rooms'),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='room_pic',
            field=models.FileField(null=True, upload_to=rooms.models.user_directory_path, verbose_name='图片'),
        ),
    ]
