# Generated by Django 4.1 on 2023-01-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomcheckins_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomcheckins',
            table='room_checkins',
        ),
    ]
