# Generated by Django 4.1 on 2023-01-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomcheckins_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomcheckincustomers',
            table='room_checkin_customers',
        ),
        migrations.AlterModelTable(
            name='roomdetails',
            table='room_details',
        ),
    ]
