# Generated by Django 4.1 on 2023-01-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customers_table'),
        ('rooms', '0004_alter_roomcheckincustomers_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcheckins',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customers'),
            preserve_default=False,
        ),
    ]
