# Generated by Django 4.1 on 2023-02-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomcheckins_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcheckincustomers',
            name='room_id',
        ),
        migrations.AddField(
            model_name='roomcheckincustomers',
            name='room_checkin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.roomcheckins'),
        ),
        migrations.AddField(
            model_name='roomcheckins',
            name='check_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='roomcheckins',
            name='is_checked',
            field=models.BooleanField(default=0),
        ),
    ]
