# Generated by Django 4.1 on 2023-02-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customers_table'),
        ('rooms', '0006_remove_roomcheckincustomers_room_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomcheckincustomers',
            unique_together={('room_checkin_id', 'customer_id')},
        ),
    ]
