# Generated by Django 4.1 on 2023-02-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_rename_is_checked_roomcheckins_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheckins',
            name='check_time',
            field=models.DateTimeField(null=True),
        ),
    ]
