# Generated by Django 4.1 on 2023-02-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_roomcheckins_check_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcheckins',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
