# Generated by Django 4.1 on 2022-12-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('cellphone', models.CharField(max_length=20)),
                ('identity_card', models.CharField(max_length=20)),
                ('extra', models.CharField(max_length=1024)),
            ],
        ),
    ]
