# Generated by Django 4.1 on 2023-01-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='extra',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
