# Generated by Django 4.1 on 2023-01-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_extra'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
    ]
