# Generated by Django 4.1 on 2023-01-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customers_extra'),
        ('rooms', '0002_alter_roomcheckins_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('state', models.IntegerField()),
                ('finish_time', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customers')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomcheckins')),
            ],
        ),
    ]
