# Generated by Django 4.1 on 2023-01-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='room_id',
            new_name='room_checkin_id',
        ),
    ]
