# Generated by Django 4.1 on 2023-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_room_id_orders_room_checkin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
